services:
  frontend:
    build:
      context: ../frontend          # ruta relativa desde backend/
    container_name: finance_frontend
    env_file: ../frontend/.env.local
    ports:
      - "3000:80"
    depends_on:
      - laravel.test                # nombre del servicio PHP de Sail
